src/Indicator.vala
src/Services/Interfaces.vala
src/Services/Notification.vala
src/Services/NotificationsMonitor.vala
src/Services/NotifySettings.vala
src/Services/Session.vala
src/Utils.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationEntry.vala
src/Widgets/NotificationsList.vala
src/Widgets/SeparatorEntry.vala

Fixes the issue when updating the indicator the wingpanel crashes because of the already existing `Indicator`. Now every class is in the `Notifications` namespace. To test: navigate to `/usr/lib/x86_64-linux-gnu/wingpanel/` and duplicate `libnotifications-indicator.so` in this directory. With trunk, wingpanel will crash, with this branch, it shouldn't.

Add a namespace

---

src/Widgets/NotificationEntry.vala

Wraps notification summary/title when it is too long to fit in the popover instead of making it larger.
Before:
After:
Closes #19.

Ellipsizes notification summary when it is too long

---

src/Widgets/NotificationsList.vala

Fixes #1.
This is a fix that was proposed by @giulianofiorotto, so I decided to submit a PR here on GitHub so it can get merged. Note that the bounty should go to Giuliano, not to me. I'm just applying the same fix (without one line) and posting it here.
Original branch on LP: https://code.launchpad.net/~mr-fiorotto/wingpanel-indicator-notifications/trying-to-fix-/+merge/315178

Fix application not opening when clicking on the notification

---

cmake/GResource.cmake
data/indicator.css
data/io.elementary.wingpanel.notifications.gresource.xml
src/CMakeLists.txt
src/Indicator.vala

animating icons with Gtk.CSS.
I'm using a Gtk.Spinner here because it can be used with `-gtk-icon-source`. It doesn't seem Gtk.Image works with it which is weird. I can't use the `background-image` property because it doesn't respect `-gtk-icon-shadow`.

CSS icon change

---

src/Widgets/AppEntry.vala

* Bump license
* Use grid instead of box
* Use style constants
* Fixes #38 by setting image pixel size

AppEntry.vala: cleanups and fix icon size

---

src/Widgets/AppEntry.vala

Fixes an oops with the change to Gtk.Grid. Make sure we expand the label so the clear button is pushed to the end

Fix a regression with clear button alignment

---

src/Widgets/NotificationEntry.vala

* Bump copyright header
* Reduce variable scope where possible
* GObject-style construction
* Remove unnecessary cast for xalign
* Properties in alphabetical order
* Keep grid properties and methods together
* Signals at the end

NotificationEntry: GObject-style and other cleanup

---

debian/control

As per @danrabbit request
> Hm it looks like dbus-glib is mentioned in the packaging. If this isn't necessary we should make sure to remove it from there as well

debian: Remove dbus-glib dependency

---

src/Indicator.vala

Using same class as other indicators. 
Fixes: #69

Fix top margin popover

---

src/Indicator.vala

* Replace box with Grid
* Removed unused constant
* Only fetch `dynamic_icon` context once
* Replace deprecated `Wingpanel.Widgets.AutomaticScrollBox`
* Remove unused label
* Signals at the end

Indicator: misc cleanup

---

data/notifications.appdata.xml.in
meson.build
src/Services/Notification.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationsList.vala

Fixes #68 
Fixes #10 
Drop the cutesy Wnck stuff. If notifications should be removed, the app can withdraw them or we can do something at the notification server level to withdraw notifications.

Remove Wnck

---

src/Indicator.vala

This lead to several warnings as `switch_stack` was being called without dynamic_icon even being a thing

Indicator: fix the state restoration

---

src/Indicator.vala

Is is used by the signal callbacks of get_display_widget and get_widget so we always need it

Indicator: Initialize app_settings_cache in all cases

---

src/Services/Interfaces.vala
src/Services/Notification.vala
src/Services/NotificationsMonitor.vala

They were switched for some unknown reason leading to incompatibility with the specification

D-Bus: Fix the ActionInvoked parameters

---

src/Indicator.vala

The docs on  SettingsSchemaSource get_default say
```
The returned source may actually consist of multiple schema sources from different directories, depending on which directories were given in `XDG_DATA_DIRS` and `GSETTINGS_SCHEMA_DIR`. For this reason, all lookups performed against the default source should probably be done recursively.
```
Without this in NixOS, it will always use gala notifications
because recursion is required. It would be nice if any new code
in Pantheon always works like this to support NixOS properly.
---
I noticed this in https://github.com/elementary/notifications/issues/62#issuecomment-609579829.

Indicator: Lookup io.elementary.notifications recursively

---

src/Widgets/NotificationEntry.vala

Copies rules from https://github.com/elementary/notifications/blob/master/src/Bubble.vala#L102
* Consistent width: always 33ch wide
* Titles ellipsize, not wrap
* Body can be a maximum of 2 lines
* Forcefully remove extra new lines in body if necessary and truncate each line independently 
Also make timestamps dim label as we do in Mail

NotificationEntry: Copy line length and truncate rules

---

src/Widgets/NotificationsList.vala

It turns out we run the same loop twice in these single-use methods. This should make it easier to follow what this method actually does

NotificationsList: simplify add_entry_internal

---

src/Indicator.vala
src/Widgets/NotificationsList.vala

Instead of manually updating, we can use listbox's built-in add and remove signals to make sure that we're always accurate no matter how the list is changed

Indicator: Connect to built-in listbox signals

---

src/Widgets/NotificationEntry.vala

Instead of waiting for the time changed signal. This fixes an issue where all notifications say "Now" on startup

NotificationEntry: Set the correct time label on construct

---

src/Services/Notification.vala
src/Services/Session.vala

Since this is only used for saving the session, we can convert from GLib.DateTime on save and restore. This doesn't need to be a property

Notification: Remove unix time property

---

src/Services/Notification.vala
src/Widgets/NotificationEntry.vala

We set the timestamp by default on construct so this doesn't appear to do anything

Notification: Remove data session property

---

src/Services/Notification.vala
src/Services/Session.vala

Turns out we were hardcoding this to `0`

Session: Save/Restore replaces_id

---

data/NotificationEntry.css
src/Widgets/NotificationEntry.vala

Adds the ability to remove one notification at a time while on Desktop. Other form factors untested.
Looks like this:
CAVEAT: Place of activation seems to be small (2 pixels :disappointed: ), and the layout of each notification becomes off... If you have any ideas to help fix this, do voice 'em in the comments/reviews.

[Desktop] Per-notification Delete Button

---

src/Widgets/AppEntry.vala
src/Widgets/NotificationEntry.vala

#149 significantly increased spacing between bubbles to accommodate the close button, so this tightens it up just a little

Reduce spacing between bubbles

---

src/Indicator.vala
src/Services/Notification.vala

Avoid an issue with possibly null appinfo and only assign fallback ID in one place

Move UsesNotifications check to Notification

---

src/Indicator.vala
src/Services/Notification.vala

Instead of `get_is_valid` function. This allows us to make hints private to the dbus message constructor and makes it more clear what we mean by "valid"

Notification: Add is_transient property

---

src/Indicator.vala
src/Widgets/NotificationsList.vala

In the future when we support replaces, we don't always want to construct a new NotificationEntry every time we get a notification. Having this internal to the `add_entry` method means the notification list will be able to make a determination about whether to construct a new entry or not

Handle NotificationEntry construction in NotificationsList

---

src/Services/Notification.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationEntry.vala

This does two things:
1. Makes it easier for me to implement "replaces" which I swear is coming eventually
2. Makes it explicit what the purpose of this thing is and make sure we do it whenever we remove a NotificationEntry

Notification: add stop_timeout

---

src/Widgets/AppEntry.vala
src/Widgets/NotificationsList.vala

Doesn't make anything else support `null` app info yet, but theoretically you should be able to construct an AppEntry without app_info now

AppEntry: Support null appinfo

---

src/Services/Notification.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationEntry.vala

`app_info` is never null, so this doesn't work as intended
This should fix notification icons for apps with no `app_info` that are trying to set an icon manually and actually fall back to `dialog-information` if none is available. Neat!
One problem you'll experience is that your restored notifications that were sent prior to this branch will all be `dialog-information` because we were never properly setting or storing these icons. But this won't happen for any new icons

Fix notification icons

---

src/Indicator.vala

Closes #173.
<strike>As for showing middle-click to enable/disable DnD, I can't parse a mouse key to Granite.markup_accel_tooltip since it takes **keyboard** accelerators.</strike>

Add notifications indicator tooltip

---

src/Indicator.vala

Requires elementary/granite#474
`Wingpanel.Widgets.Switch` and `Wingpanel.Widgets.Separator` are deprecated.

Use Granite.SwitchModelButton and Gtk.Separator

---

src/Services/Session.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationsList.vala

Fixes #174 
- Add a `remove_notifications` method to `Session` so that a bunch of notifications can be removed at once, with a single disk write instead of writing the changes to the disk in between each removal.
- Remove `async` that wasn't actually async
- Don't remove entries from a `HashMap` in a read-only foreach loop.
- Disconnect a clear signal handler to prevent circular signal emissions

Notification clearing fixes

---

src/Services/Notification.vala

If we're getting valid appinfo, we shouldn't force apps to be listed under "Other"

Notification: Don't rewrite valid appinfo

---

src/Widgets/NotificationsList.vala

This is strangely convoluted. The only types of things packed into this listbox are either notifications or app headers, so there's no case where `close == false`. It also doesn't make sense to clear all notifications unless the user clicks the clear all button in the header. So really we only need to check if a notification has been activated here

NotificationsList: Don't clear all on misclick

---

src/Services/Interfaces.vala
src/Services/NotificationsMonitor.vala

Fixes #210 
The eavesdropping method of listening to messages on the bus is deprecated according to the DBus docs https://dbus.freedesktop.org/doc/dbus-specification.html
The replacement is setting a private bus connection up as a "Monitor".
I've tested this restores the functionality of the notification indicator on Fedora, where nothing was happening, presumably due to newer versions of DBus or stricter blocking of the older eavesdropping method. I've also tested that this continues to work on Odin.
I've also replaced the `error` calls with more appropriate things. We shouldn't crash the whole of wingpanel just because notifications aren't working properly.

NotificationsMonitor: Replace deprecated eavesdrop monitoring

---

src/Services/NotificationsMonitor.vala

This changed in https://gitlab.gnome.org/GNOME/vala/-/commit/9d5708923f64b3914aa213ca780973be853a03b7
@decathorpe Can you see if this fixes compilation for you on Fedora 35?

NotificationsMonitor: Support Vala 0.54+

---

src/Services/NotificationsMonitor.vala

The DBusMessage body can be null, handle this case by letting the message go through.
Also remove the temporary variant reference while filtering.

NotificationsMonitor: Handle null body in message_filter

---

src/Indicator.vala
src/Services/NotificationsMonitor.vala
src/Services/Session.vala
src/Widgets/AppEntry.vala
src/Widgets/NotificationsList.vala

When clearing all notifications do not rewrite the session file for each notification closed.
This reduces the time take to clear an app's notifications from minutes to seconds when there are >1000 notifications.
Also reduces the complexity of code to clear an app's notifications.
Also incorporates some of #241 for convenience when testing - allows notifications to be added more quickly.

Clear notifications faster

---

src/Indicator.vala
src/Widgets/NotificationsList.vala

- Set `width_request` of `NotificationsList` to 360 (standard size of a notification)
- Prevent the indicator from resizing when all notifications are cleared
Before:
After:

Constant indicator width

---

src/Indicator.vala
src/Services/Notification.vala
src/Services/NotificationsMonitor.vala
src/Services/Session.vala
src/Widgets/NotificationEntry.vala
src/Widgets/NotificationsList.vala

At present if a notification bubble is actively dismissed it remains in the wingpanel list and has to be dismissed again to get rid of it. This seems unexpected.  This PR removes notifications from the list if they are actively closed by the user or a  "CloseNotification" method call. 
It is open to question whether this should also happen in reverse i.e. urgent bubbles should disappear if cleared from the wingpanel list (at present they do not) but that is left for another PR (after hiding bubbles when the indicator is open is implemented).
There was existing code in the NotificationsMonitor that appeared to be intended to implement this already but it did not detect NotificationClosed signals.
A superfluous function/signal was removed from Notification; the Indicator detects when a …

Remove notification from list if bubble dismissed; give accurate tooltip count

---

data/NotificationEntry.css
src/Widgets/NotificationEntry.vala

Can be rebase merged if desired
* Code style. Use child property for revealers, overlays, etc
* Adding providers to a style context is deprecated
* Prefer CSS to markup where possible
* No "add" in grid

NotificationEntry: GTK4 prep
