CMakeLists.txt, config.vala.cmake, src/CMakeLists.txt, src/Services/Notification.vala, src/Widgets/NotificationEntry.vala
Use relative date time util from Granite instead of own util here
=> NotificationEntry.vala: Use Granite.DateTime

src/Indicator.vala
Set the actual state of the icon (no notifications, do not disturb or has notifications) in the `get_display_widget` instead of doing that in `get_widget`. While we're here I moved some things to their appropriate location to not initialize them in the construct block.
=> Set icon state in get_display_widget

src/Indicator.vala
Fixes #48.
Moves important initialization from `get_widget` to `get_display_widget` so that the indicator can still persist notifications and change disturb state without opening the indicator.
=> Fix status not updating when the indicator was not opened before

src/Indicator.vala
=> Create stack change handler before widget creating

README.md
=> README.md: Remove dbus-glib dependency

src/Widgets/AppEntry.vala
* Update copyright header
* GObject-style construction
* `app_info` is nullable
* Use `gicon` when it's available
=> AppEntry: misc cleanup

src/Indicator.vala
=> Indicator: bind DnD to new setting if available

src/Services/Notification.vala, src/Widgets/NotificationsList.vala
=> Launch default action on click

src/Indicator.vala
=> Fix button sensitivity setting for clear all notifications

src/Indicator.vala
Fix https://github.com/elementary/switchboard-plug-notifications/issues/73
=> Fix settings scheme for remember option

src/Widgets/AppEntry.vala
=> AppEntry: use clear-all icon and add tooltip

src/Services/Notification.vala
Since this is done for both constructors
=> Notification: set timeout in construct

data/indicator.css
=> Indicator.css: Fix incorrect opacity

src/Services/Notification.vala
=> Notification: remove PID

src/Services/Notification.vala
This does not appear to ever be used
=> Notification: Remove unused expire timeout

src/Widgets/NotificationsList.vala
=> NotificationsList: Fix clear all

src/Services/Notification.vala, src/Widgets/NotificationEntry.vala
This is purely for UI, so it doesn't make sense to have this in the notification object
=> Move timeout to NotificationEntry

meson.build, src/Config.vala.in, src/Indicator.vala
To follow @tintou's recent work on other projects
=> Use config file to get the project name

src/Services/Notification.vala, src/Widgets/NotificationEntry.vala
Fixes icons for Chrome and possibly other apps
=> Show app icons from URIs

data/image-mask.svg, data/io.elementary.wingpanel.notifications.gresource.xml, meson.build, src/Services/Notification.vala, src/Services/Session.vala, src/Widgets/MaskedImage.vala, src/Widgets/NotificationEntry.vala
Nearly all of this code is copied from the Notifications server. Some tiny adaptations made in Notification and Session
Brings us to parity with the notifications server
=> Support image paths and badges

src/Services/Notification.vala
same as elementary/notifications#122.
=> Do Not Read AppInfo From Autostart Dir

src/Services/NotificationsMonitor.vala
Allows to start the indicator without having to wait for it to be connected
to the session bus.
Fixes #234
=> NotificationsMonitor: Asynchronously register the service

src/Indicator.vala, src/Widgets/AppEntry.vala, src/Widgets/NotificationsList.vala
=> Fix operation of Clear All button

src/Widgets/NotificationEntry.vala
Fixes #231 
Closes #232
Based on #232
Requires https://github.com/elementary/notifications/pull/184
=> Add full markup support

data/AppEntryExpander.css, src/Widgets/AppEntry.vala
* allow focusing so we can interact via keyboard
* `image-button` class handles almost everything for us already, just make sure we remove the background when :checked
* Fix `:focus` background color
* Fix label font weight
* Add a tooltip to the arrow image
=> Make headers focusable, fix styles, add tooltip

.github/workflows/ci.yml, meson.build
Looks like we got rid of this a while go but didn't update CI
=> CI: Remove Wnck

src/Indicator.vala, src/Widgets/NotificationsList.vala
Can be rebase merged if desired
=> Indicator: GTK4 prep

src/Widgets/NotificationsList.vala
Can't get children like this in GTK4
=> NotificationsList: use get_row_at_index

src/Indicator.vala, src/Widgets/NotificationsList.vala
Can't subclass listbox in GTK4
=> NotificationsList: subclass Bin
